[tool.poetry]
name = "hello"
version = "1.6.1"
description = ""
authors = ["glennlum <glennlum_@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
